Add Taptic Engine
gontovnik/DGRunkeeperSwitch pull request #42
Opened 2017-03-05 20:26 UTC by RemyDCF

2017-03-06 21:22 UTC, efremidze commented
can u explain more?

2017-03-06 21:31 UTC, RemyDCF commented
If you have an iPhone 7/7 Plus, it produce a haptic feedback provided by Taptic Engine. I added it to confirm to the user that the selected index was changed

2017-03-27 16:41 UTC, gontovnik commented
Please make it optional and configurable. I believe that not every person who uses it in his project really wants that.

2017-03-27 16:43 UTC, gontovnik requested changes

2017-03-27 16:43 UTC, gontovnik commented on DGRunkeeperSwitch/DGRunkeeperSwitch.swift
> +            }
Please make it optional.

2017-03-27 20:19 UTC, RemyDCF commented on DGRunkeeperSwitch/DGRunkeeperSwitch.swift
> +            }
Done

2017-04-02 15:58 UTC, RemyDCF commented
I made the changes

2017-07-05 16:02 UTC, gontovnik commented on DGRunkeeperSwitch/DGRunkeeperSwitch.swift
> +    open var impactFeedbackActivated: Bool = false
Please replace with the `impactFeedbackEnabled` and I will merge it.

2017-07-05 16:03 UTC, gontovnik requested changes
Sorry for the delayed response. I am not active on the GitHub this year.

2017-07-05 19:37 UTC, RemyDCF commented on DGRunkeeperSwitch/DGRunkeeperSwitch.swift
> +    open var impactFeedbackActivated: Bool = false
Done

2018-04-20 07:50 UTC, closed without merging